import Foundation

/// Decides whether a pasteboard change may be recorded. Honors the password-manager conventions unconditionally.
enum PasteboardFilter {
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-sensitive",
        "com.agilebits.onepassword",
    ]

    static func shouldRecord(types: [String]) -> Bool {
        !types.contains { excludedTypes.contains($0) }
    }
}
