(module 
(import "wasi_snapshot_preview1" "fd_read" (func $read (param i32 i32 i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "fd_write" (func $write (param i32 i32 i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "fd_close" (func $close (param i32) (result i32)))
(import "wasi_snapshot_preview1" "fd_fdstat_get" (func $stat (param i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "fd_seek" (func $seek (param i32 i64 i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "environ_sizes_get" (func $envsize (param i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "environ_get" (func $env (param i32 i32) (result i32)))
(import "wasi_snapshot_preview1" "clock_time_get" (func $clock (param i32 i64 i32) (result i32)))
(import "wasi_snapshot_preview1" "proc_exit" (func $exit (param i32))) (memory (export "memory") 1 1) (data (i32.const 128) "OK")
    (func $assert (param i32) local.get 0 i32.eqz if unreachable end)
    (func (export "_start") (drop (call $read (i32.const 0) (i32.const 0) (i32.const 1025) (i32.const 8)))))
